list: $/synoptica/product/models/type/columns.yaml
modelClass: Synoptica\Product\Models\Type
title: Types
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'synoptica/product/types/update/:id'
