list: $/synoptica/product/models/product/columns.yaml
modelClass: Synoptica\Product\Models\Product
title: Products
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'synoptica/product/products/update/:id'
